FROM python:3.7

ARG ENV=local

WORKDIR /backend
COPY . /backend

RUN pip install -r requirements.txt --no-cache-dir && \
    apt update && \
    apt install -y cron


CMD python manage.py runserver 0.0.0.0:8000
